USE sql10498921;

DROP TABLE IF EXISTS SellsProducts;
DROP TABLE IF EXISTS Sells;
DROP TABLE IF EXISTS ProductsTypeCategory;
DROP TABLE IF EXISTS CartsProductsTypes;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS ProductsTypes;
DROP TABLE IF EXISTS Shops;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Carts; 

